src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 * @Vich\Uploadable
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $summary;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_of_page;

    /**
     * @ORM\Column(type="date")
     */
    private $date_parution;

    /**
     * @ORM\ManyToOne(targetEntity=Bibliotheque::class, inversedBy="livres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bibliotheque;

    /**
     * @ORM\ManyToOne(targetEntity=Auteur::class, inversedBy="livres")
     */
    private $auteur;

    /**
     * @ORM\ManyToMany(targetEntity=Vitrine::class, mappedBy="livres")
     */
    private $vitrines;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $imageName;

    /**
     * @Vich\UploadableField(mapping="livres_img", fileNameProperty="imageName")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTime
     */
    private $imageUpdatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Type::class, inversedBy="livres")
     */
    private $types;

    public function __construct()
    {
        $this->vitrines = new ArrayCollection();
        $this->types = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getNumberOfPage(): ?int
    {
        return $this->number_of_page;
    }

    public function setNumberOfPage(int $number_of_page): self
    {
        $this->number_of_page = $number_of_page;

        return $this;
    }

    public function getDateParution(): ?\DateTimeInterface
    {
        return $this->date_parution;
    }

    public function setDateParution(\DateTimeInterface $date_parution): self
    {
        $this->date_parution = $date_parution;

        return $this;
    }

    public function getBibliotheque(): ?Bibliotheque
    {
        return $this->bibliotheque;
    }

    public function setBibliotheque(?Bibliotheque $bibliotheque): self
    {
        $this->bibliotheque = $bibliotheque;

        return $this;
    }

    public function __toString(): string
    {
        return '[' . $this->id . '] ' . $this->titre;
    }

    public function getAuteur(): ?Auteur
    {
        return $this->auteur;
    }

    public function setAuteur(?Auteur $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    /**
     * @return Collection<int, Vitrine>
     */
    public function getVitrines(): Collection
    {
        return $this->vitrines;
    }

    public function addVitrine(Vitrine $vitrine): self
    {
        if (!$this->vitrines->contains($vitrine)) {
            $this->vitrines[] = $vitrine;
            $vitrine->addLivre($this);
        }

        return $this;
    }

    public function removeVitrine(Vitrine $vitrine): self
    {
        if ($this->vitrines->removeElement($vitrine)) {
            $vitrine->removeLivre($this);
        }

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->imageUpdatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @return Collection<int, Type>
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        $this->types->removeElement($type);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('bibliotheque', null, [
                'disabled' => true,
            ])
            ->add('titre')
            ->add('summary')
            ->add('number_of_page')
            ->add('date_parution')
            ->add('auteur')
            ->add('types')
            ->add('imageName', TextType::class,  ['disabled' => true])
            ->add('imageFile', VichImageType::class, ['required' => false]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Bibliotheque;
use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

/**
 * @Route("/livre")
 */
class LivreController extends AbstractController
{
    /**
     * @Route("/", name="app_livre_index", methods={"GET"})
     */
    public function index(Request $request, LivreRepository $livreRepository): Response
    {
        if ($this->isGranted('ROLE_ADMIN')) {
            $livres = $livreRepository->findAll();
        } else {
            /** @var \App\Entity\User */
            $user = $this->getUser();
            if ($user) {
                $membre = $user->getMembre();
                $livres = $livreRepository->findMemberLivres($membre);
            } else {
                throw $this->createAccessDeniedException("You cannot access livres without connection!");
            }
        }
        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/favorite", name="app_livre_index_favorite", methods={"GET"})
     */
    public function indexFavorite(Request $request, LivreRepository $livreRepository): Response
    {
        $urgents = $request->getSession()->get('urgents');
        if ($urgents == null) {
            $urgents = [];
        }
        $livres = $livreRepository->findAll();
        // Filter by id in urgent array
        $livres = array_filter($livres, function ($livre) use ($urgents) {
            return in_array($livre->getId(), $urgents);
        });
        return $this->render('livre/index_favorite.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/new/{id}", name="app_livre_new", methods={"GET", "POST"})
     */
    public function new(Request $request, LivreRepository $livreRepository, Bibliotheque $bibliotheque): Response
    {
        $hasAccess = $this->isGranted('ROLE_ADMIN') ||
            ($this->getUser() != null && $this->getUser() == $bibliotheque->getMembre()->getUser());
        if (!$hasAccess) {
            throw $this->createAccessDeniedException("You cannot edit another member's bibliotheque livre!");
        }

        $livre = new Livre();
        $livre->setBibliotheque($bibliotheque);
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->add($livre, true);
            $this->addFlash('message', 'bien ajouté');

            return $this->redirectToRoute('app_bibliotheque_show', ['id' => $bibliotheque->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        $hasAccess = $this->isGranted('ROLE_ADMIN') ||
            ($this->getUser() != null && $this->getUser() == $livre->getBibliotheque()->getMembre()->getUser());
        if (!$hasAccess) {
            throw $this->createAccessDeniedException("You cannot view another member's bibliotheque livre in private!");
        }

        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_livre_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        $hasAccess = $this->isGranted('ROLE_ADMIN') ||
            ($this->getUser() != null && $this->getUser() == $livre->getBibliotheque()->getMembre()->getUser());
        if (!$hasAccess) {
            throw $this->createAccessDeniedException("You cannot edit another member's bibliotheque livre in private!");
        }

        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->add($livre, true);

            return $this->redirectToRoute('app_bibliotheque_show', ['id' => $livre->getBibliotheque()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_livre_delete", methods={"POST"})
     */
    public function delete(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        $hasAccess = $this->isGranted('ROLE_ADMIN') ||
            ($this->getUser() != null && $this->getUser() == $livre->getBibliotheque()->getMembre()->getUser());
        if (!$hasAccess) {
            throw $this->createAccessDeniedException("You cannot delete another member's bibliotheque livre in private!");
        }

        if ($this->isCsrfTokenValid('delete' . $livre->getId(), $request->request->get('_token'))) {
            $livreRepository->remove($livre, true);
        }

        return $this->redirectToRoute('app_bibliotheque_show', ['id' => $livre->getBibliotheque()->getId()], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/livre/favorite/{id_livre}", name="app_livre_toogle_favorite", methods={"POST"})
     * @ParamConverter("livre", options={"id" = "id_livre"})
     */
    public function toogleFavorite(Request $request, Livre $livre): Response
    {
        $urgents = $request->getSession()->get('urgents');
        if (!is_array($urgents)) {
            $urgents = array();
        }
        if (in_array($livre->getId(), $urgents)) {
            $urgents = array_diff($urgents, [$livre->getId()]);
        }

        $request->getSession()->set('urgents', $urgents);

        return $this->redirectToRoute('app_livre_index_favorite', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livre/_back_form.html.twig
<a href={{ path('app_bibliotheque_show', {'id': livre.bibliotheque.id} ) }} class='btn btn-secondary'>Retour à la bibliotheque</a>

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('app_livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
	<button class="btn btn-danger">Delete</button>
</form>

templates/livre/_favorite_form.html.twig
<form method="post" action={{ path('app_livre_toogle_favorite', {'id_livre': livre.id} ) }}>
	<button style='color: yellow' class='btn'>
		<svg width="32" height="32" viewbox="0 0 256 256">
			<path fill="currentColor" d="m132.4 190.7l50.4 32c6.5 4.1 14.5-2 12.6-9.5l-14.6-57.4a8.7 8.7 0 0 1 2.9-8.8l45.2-37.7c5.9-4.9 2.9-14.8-4.8-15.3l-59-3.8a8.3 8.3 0 0 1-7.3-5.4l-22-55.4a8.3 8.3 0 0 0-15.6 0l-22 55.4a8.3 8.3 0 0 1-7.3 5.4l-59 3.8c-7.7.5-10.7 10.4-4.8 15.3L72.3 147a8.7 8.7 0 0 1 2.9 8.8L61.7 209c-2.3 9 7.3 16.3 15 11.4l46.9-29.7a8.2 8.2 0 0 1 8.8 0Z" opacity=".2"/>
			<path fill="currentColor" d="M187.3 232a16.1 16.1 0 0 1-8.7-2.6l-50.5-31.9h-.2L81 227.2a18 18 0 0 1-20.1-.6a18.6 18.6 0 0 1-7-19.6l13.5-53.1a.8.8 0 0 0-.2-.8L22 115.5a16.8 16.8 0 0 1-5.2-18.1A16.4 16.4 0 0 1 31.4 86l59-3.8a.5.5 0 0 0 .4-.3l22-55.5a16.3 16.3 0 0 1 30.4 0l22 55.5a.5.5 0 0 0 .4.3l59 3.8a16.4 16.4 0 0 1 14.6 11.4a16.8 16.8 0 0 1-5.2 18.1l-45.2 37.6a.8.8 0 0 0-.2.8l14.5 57.3a16.6 16.6 0 0 1-6.3 17.7a16.8 16.8 0 0 1-9.5 3.1ZM128 181.5a16 16 0 0 1 8.7 2.5l50.4 31.9h.2a.7.7 0 0 0 .3-.3c.1-.1.1-.2 0-.6l-14.5-57.3a16.8 16.8 0 0 1 5.4-17l45.3-37.6c.1-.1.3-.3.1-.8s-.2-.4-.3-.4l-59.1-3.8a16.4 16.4 0 0 1-14.1-10.4l-22.1-55.4c-.1-.3-.2-.3-.3-.3s-.2 0-.3.3l-22.1 55.5a16.4 16.4 0 0 1-14.1 10.4L32.4 102c-.1 0-.2 0-.3.4s0 .7.1.8l45.3 37.6a16.8 16.8 0 0 1 5.4 17L69.4 211a2.5 2.5 0 0 0 .9 2.6a1.6 1.6 0 0 0 2.1.1l46.9-29.7a16 16 0 0 1 8.7-2.5Z"/>
		</svg>
	</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre
{% endblock %}

{% block main %}
	<h1>Edit Livre</h1>

	{{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

	{{ include('livre/_back_form.html.twig') }}

	{{ include('livre/_delete_form.html.twig') }}
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index
{% endblock %}

{% block main %}
	<h1>Livre(s)</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Titre</th>
				<th>Summary</th>
				<th>Number_of_page</th>
				<th>Date_parution</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for livre in livres %}
				<tr>
					<td>{{ livre.id }}</td>
					<td>{{ livre.titre }}</td>
					<td>{{ livre.summary }}</td>
					<td>{{ livre.numberOfPage }}</td>
					<td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
					<td>
						<a href="{{ path('app_livre_show', {'id': livre.id}) }}">show</a>
						<a href="{{ path('app_livre_edit', {'id': livre.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/livre/index_favorite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres index favoris
{% endblock %}

{% block main %}
	<h1>Livre(s) favoris</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Titre</th>
				<th>Summary</th>
				<th>Number_of_page</th>
				<th>Date_parution</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for livre in livres %}
				<tr>
					<td>{{ livre.id }}</td>
					<td>{{ livre.titre }}</td>
					<td>{{ livre.summary }}</td>
					<td>{{ livre.numberOfPage }}</td>
					<td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
					<td>{{ include('livre/_favorite_form.html.twig') }}</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre
{% endblock %}

{% block main %}
	<h1>Create new Livre</h1>

	{{ include('livre/_form.html.twig') }}

	{{ include('livre/_back_form.html.twig') }}
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre
{% endblock %}

{% block main %}
	<h1>Livre</h1>
	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ livre.id }}</td>
			</tr>
			<tr>
				<th>Titre</th>
				<td>{{ livre.titre }}</td>
			</tr>
			<tr>
				<th>Summary</th>
				<td>{{ livre.summary }}</td>
			</tr>
			<tr>
				<th>Number_of_page</th>
				<td>{{ livre.numberOfPage }}</td>
			</tr>
			<tr>
				<th>Date_parution</th>
				<td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
			</tr>
			{% if livre.imageName %}
				<tr>
					<th>Image</th>
					<td><img src={{ vich_uploader_asset(livre, 'imageFile') }}/></td>
				</tr>
			{% endif %}
		</tbody>
	</table>

	{{ include('livre/_back_form.html.twig') }}

	<a href={{ path('app_livre_edit', {'id': livre.id} ) }} class='btn btn-primary'>edit</a>

	{{ include('livre/_delete_form.html.twig') }}
{% endblock %}